### ISSUE TITLE
[BUG] Command Board Crashes! - BBS

### ISSUE THREAD

**Issue by Crissmore** [TopazTK/KH-ReFixed#49]
Re:Fixed Version:
v2.90 (no dual audio)

Game in Question:
Kingdom Hearts - Birth by Sleep

Bug Description:
Game Crashes when i try to open the command board
Right now, the crash spots are:

Command Board

Reproduction Steps:
Open the command board playing as Terra (first gameplay) from the world selection.

Screenshots/Video:
Not needed.

**Comment by TopazTK** [comment]
That's odd if it crashes without Dual Audio.
Investigating.

**Comment by TopazTK** [comment]
Investigation done! BBS turned out to be highly unstable due to an error on my part.
It should be fixed as of 120e17e070ab801fdaf7075cb3658ff88d87f620, but I will check once more.
Closing temporarily, permanently if fixed.

**Comment by git123userhub** [comment]
how come i still get this then? it still happens for me :(
the problem is the fact that i cant easily reproduce this, because it only happens as a random chance when an AI steps on one of the special blocks (special blocks on keyblade map at the far right at the blade half)

**Comment by TopazTK** [comment]
BBS is still sorta kinda borked, will be fixed completely in v4.00
However, the crashes can be the result of the port just being silly.
